export interface banco {
    bban?: string,
    bic?: string,
    cla?: string,
    cod?: string,
    cu1?: string,
    cu2?: string,
    cu3?: string,
    cu4?: string,
    dir?: string,
    epri?: string,
    fman?: string,
    hab?: string,
    iban?: string,
    id?: string,
    nman?: string,
    nom?:string,
    npro?: string,
    pais?: string,
    pob?: string,
    pro?: string,
    trem?: string,
}