export interface direccion {
    cla?: string,
    cod?: string,
    den?: string,
    dir?: string,
    email?: string,
    hab?: string,
    id?: string,
    npro?: string,
    pais?: string,
    per?: string,
    pob?: string,
    pro?: string,
    rut?: string,
    tel?: string,
}